server:
  port: 8080
sip:
  sipServer: 172.16.2.19
  sipPort: 8060
  mrcpServerPort: 1544
mrcp:
  # xfyun、funasr
  asrMode: funasr
  # xfyun、kokoro
  ttsMode: kokoro
rtp:
  # asr的rtp端口范围
  asrStartPort: 5000
  asrStopPort: 6000
  # tts的rtp端口范围
  ttsStartPort: 15000
  ttsStopPort: 16000