server:
  # 服务端口
  port: 8080
sip:
  # EasyMrcp要监听的sip服务器地址，填写项目运行的ip地址
  sipServer: 192.168.31.30
  # sip服务器端口
  sipPort: 8060
  # mrcp服务器端口
  mrcpServerPort: 1544
mrcp:
  # 选择一个asr服务，目前已经集成：xfyun、funasr、tencent-cloud
  asrMode: xfyun
  # 选择一个tts服务，目前已经集成：xfyun、kokoro、tencent-cloud
  ttsMode: xfyun
rtp:
  # asr的rtp端口范围
  asrStartPort: 5000
  asrStopPort: 6000
  # tts的rtp端口范围
  ttsStartPort: 15000
  ttsStopPort: 16000